spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.168.63.232:3307/zhwg_trans_conf?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
